### ISSUE TITLE
I try to use this in Lucee.

### ISSUE THREAD

**Issue by DrunkenMoose** [yeokm1/docs-to-pdf-converter#15]
Hey Yeokm,

I found your library and It's exactly what I need. A simple solution that independently converts docx to pdf. I've got it working under windows with the command line. And this works perfect! Good log messages, and the generated pdf is placed next to the docx. 

Now I got this project running with Lucee. This is a sub application of coldfusion that is based on Java. In lucee I can add JAR files and call them in the code. But if I do this then I get an error saying it cannot find "org/apache/poi/xwpf/converter/core/Options". This error comes within the JAR file. I've explained the full problem here: https://stackoverflow.com/questions/50086006/lucee-with-docs-to-pdf-converter

Any help with this is really appreciated. Have you ever gotten a NoClassDefFound error while using this? I just find it weird that it works as a JAR file but not in our project. 

Thanks in advance,
Roland M

**Comment by DrunkenMoose** [comment]
Hey again,

I still thought this library could be something very useful for me, so I thought let's go forth with troubleshooting. I asked around and did some digging of my own. But someone made a jar file that could work with my Lucee 5.0 version. Here is a link to the discussion: https://dev.lucee.org/t/lucee-jar-problem-noclassdeffounderror/3834 

I did a quick test but it succesfully converted a docx to pdf. So thanks for the library, I will go find a donate button where I can give some bucks for a coffee for a little thanks. For the trouble making the library.

**Comment by yeokm1** [comment]
Sorry I was busy the past few days. Great to know you found a solution! As for donations, I don't mind! :) I have dropped you an email.
